### ISSUE TITLE
Froze while Display=True; 0 Successes/Failures; NoneType error

### ISSUE THREAD

**Issue by LecJackS** [llSourcell/Game-AI#2]
**1.** Tried --display True 

Shows space invaders game while playing randomly. Dies 3 times. Freezes at 0 lives every time.

Apparently it keeps populating memory because memory size keeps increasing (really slowly) and then starts training (space invaders window keeps frozen).

**2.** Trained for 500,000 steps (default). Similar results with --train-steps 1000.

Successes, Failures, Successe samples and Failure samples always 0.

```
memory size:  50992 
Training steps:  992 
Learning rate:  0.9991081 
Successes:  0 
Failures:  0 
Successe samples:  0 
Failure samples:  0 
Average batch loss:  0.0018958834396 
Batch training time:  0.072449631989 
```

**3.** NoneType error while training ends:

```
Traceback (most recent call last):
  File "atari.py", line 61, in <module>
    env.gym.monitor.start(args.out, force=True)
  File "/home/jacks/.local/lib/python2.7/site-packages/gym/monitoring/monitor.py", line 116, in start
    if not os.path.exists(directory):
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by holynakamoto** [comment]
I couldn't get the display to output then I set this to True and it works...

**Comment by holynakamoto** [comment]
@LecJackS Yes I am seeing the same now...

**Comment by llSourcell** [comment]
Hmm I'm trying to figure out what's going wrong here.

**Comment by holynakamoto** [comment]
Also tried another env

```
[2016-05-17 11:18:31,584] Making new env: Go9x9-v0
Initializing Pachi engine uct with args threads=1,pondering=0
Initializing Pachi engine uct with args threads=1,pondering=0
To play: black
Move:   0  Komi: 0.0  Handicap: 0  Captures B: 0 W: 0
      A B C D E F G H J
    +-------------------+
  9 | . . . . . . . . . |
  8 | . . . . . . . . . |
  7 | . . . . . . . . . |
  6 | . . . . . . . . . |
  5 | . . . . . . . . . |
  4 | . . . . . . . . . |
  3 | . . . . . . . . . |
  2 | . . . . . . . . . |
  1 | . . . . . . . . . |
    +-------------------+
OpenCV Error: Assertion failed (depth == CV_8U || depth == CV_16U || depth == CV_32F) in cvtColor, file /Users/nicholasmoore/opencv/modules/imgproc/src/color.cpp, line 7935
Traceback (most recent call last):
  File "atari.py", line 58, in <module>
    Trainer(agent).run()
  File "/Users/nicholasmoore/Game-AI/train.py", line 15, in run
    self.agent.randomRestart()
  File "/Users/nicholasmoore/Game-AI/dqn.py", line 74, in randomRestart
    state = self.env.getScreen()
  File "/Users/nicholasmoore/Game-AI/environment.py", line 27, in getScreen
    return cv2.resize(cv2.cvtColor(self.observation, cv2.COLOR_RGB2GRAY), self.dims)
cv2.error: /Users/nicholasmoore/opencv/modules/imgproc/src/color.cpp:7935: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cvtColor
```

**Comment by llSourcell** [comment]
ok @LecJackS and @rasheedmoore I went ahead and pushed a fix for the NoneType error and success & failure giving all zeros. It should work now!

**Comment by LecJackS** [comment]
@llSourcell Nice!

About the zeros, it works perfectly:

```
Training step:  992 
memory size:  50992 
Learning rate:  0.9991081 
Successes:  12 
Failures:  50213 
Sample successes:  1 
Sample failures:  7815 
Average batch loss:  0.00578377395459 
Batch training time:  0.0798742845654 s
```

About the NoneType, its still there :/

Maybe is something about my gym installation? Have some problems at the beginning, but then I installed it and worked fine.

```
Traceback (most recent call last):
  File "atari.py", line 61, in <module>
    env.gym.monitor.start(args.out, force=True)
  File "/home/jacks/.local/lib/python2.7/site-packages/gym/monitoring/monitor.py", line 116, in start
    if not os.path.exists(directory):
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

About the freeze, I tried some changes and worked. Don't know if it's the nicer way to do it, but works (or it seems to).

In the Environment.py file, modified this:

```
    def act(self, action):
        if self.display:
            self.gym.render()
        self.observation, reward, self.terminal, info = self.gym.step(action)
        return reward
```

To this:

```
    def act(self, action):
        if self.display:
            self.gym.render()
        self.observation, reward, self.terminal, info = self.gym.step(action)
        if self.terminal:
            print "No more lives, restarting"
            self.gym.reset()
        return reward
```

**Comment by holynakamoto** [comment]
It's working for me now, also if anyone is trying to install opencv on a mac using conda they should use:

```
conda install -c condo-forge opencv

```

**Comment by llSourcell** [comment]
@rasheedmoore awesome!! @LecJackS hmm. Some people have had success by wrapping the string that is being returned in the unicode function i.e 'return unicode(my_string) http://stackoverflow.com/questions/16169035/coercing-to-unicode-need-string-or-buffer-nonetype-found-when-rendering-in-dja 

Or maybe its expecting a command line argument '    env.gym.monitor.start(args.out, force=True)' like the name of a game instead of default.

**Comment by LecJackS** [comment]
@llSourcell I think the problem was there was no args.out default. I printed it, and there was nothing there. If I added a directory manually, it worked, but when there was no --out argument, there was no place to save what gym generates at the end of the training.

So I added a couple of lines to do that, and worked!

I tested it a couple of times with different values and arguments, and it worked.

It creates a gym output folder (gym-out) and inside it, another one with the game's name.

I upload the code, so you can see it there. There was no big changes.

**Comment by holynakamoto** [comment]
Thanks Siraj, 

Everything worked fine for me once I merged, I do however notice that the success rate seems to be stagnant.  Going to try to play around with the code a little later to see if I can improve on that.

Training step:  175776
memory size:  100000
Learning rate:  0.8418025
Successes:  1348
Failures:  921
Sample successes:  8366
Sample failures:  5652
Average batch loss:  0.155652640387
Batch training time:  0.0333953127265 s

**Comment by LecJackS** [comment]
All issues from here were solved, so I'm closing this.
